---
IOS1:
  hostname: 192.168.29.131
  groups:
    -IOS_Routers123

IOS2:
  hostname: 192.168.29.132
  groups:
    -IOS_Routers123
    
IOS2:
  hostname: 192.168.29.132
  groups:
    -IOS_Routers123    
